### ISSUE TITLE
Don't understand, why/hoe declare module ....?

### ISSUE THREAD

**Issue by thearabbit** [ics-software-engineering/meteor-application-template-react-typescript#3]
Ex:
```
/* eslint-disable */
/* Declaring in the format prescribed by Meteor */
declare module "meteor/themeteorchef:bert" {
  export class BertAlert {
    constructor();
    alert({});
  }
  export const Bert: BertAlert;
}
```

**Comment by cammoore** [comment]
That code is in the file app/imports/typings/bert.d.ts. It is a type declaration for the meteor/themeteorchef:bert package. Typescript will complain when it sees "Bert.alert(...)", since the alert method is not defined on the Bert class. I created the file to tell Typescript that there is a method alert defined on the BertAlert class.

We dropped the meteor/themeteorched:bert package and are now using the sweetalert npm package for alerts.

**Comment by thearabbit** [comment]
thanks for your reply.
we need auto load the declaration this file or not?
(Where?)

**Comment by thearabbit** [comment]
For exchange `declare module "meteor/alanning:roles"`, why we know to declaration with `namespace Roles, ....` OR any methods to use?

**Comment by thearabbit** [comment]
Could We use `JS Library/Package` directly in `Typescript`???
